From 1c4a836803d579917a89d2fbc5dc8a4e9590068f Mon Sep 17 00:00:00 2001
From: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
Date: Wed, 5 Sep 2018 20:39:26 +0300
Subject: [PATCH] emulator: make log compatible with python3.5

Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
---
 backend/project/apps/telemetry_emulator/control_api.py | 6 +++---
 backend/project/apps/telemetry_emulator/sender.py      | 4 ++--
 2 files changed, 5 insertions(+), 5 deletions(-)

diff --git a/backend/project/apps/telemetry_emulator/control_api.py b/backend/project/apps/telemetry_emulator/control_api.py
index e146596..7a30bf8 100644
--- a/backend/project/apps/telemetry_emulator/control_api.py
+++ b/backend/project/apps/telemetry_emulator/control_api.py
@@ -76,19 +76,19 @@ class EmulatorCommandsRequestHandler(BaseHTTPRequestHandler):
     def _start(self):
         logger.debug("start")
         success = self.emulator.command_go()
-        logger.debug(f"success: {success}")
+        logger.debug("success: %s" % success)
         self.response(200)
 
     def _stop(self):
         logger.debug("stop")
         success = self.emulator.command_stop()
-        logger.debug(f"success: {success}")
+        logger.debug("success: %s" % success)
         self.response(200)
 
     def tire_break(self):
         logger.debug("tire_break")
         success = self.emulator.tire_break()
-        logger.debug(f"success: {success}")
+        logger.debug("success: %s" % success)
         self.response(200)
 
     def _madness(self, value):
diff --git a/backend/project/apps/telemetry_emulator/sender.py b/backend/project/apps/telemetry_emulator/sender.py
index c1adfc7..b13fffd 100644
--- a/backend/project/apps/telemetry_emulator/sender.py
+++ b/backend/project/apps/telemetry_emulator/sender.py
@@ -31,9 +31,9 @@ def sending_loop(emulator):
         try:
             _sending_loop(sc, emulator)
         except ConnectionError as ex:
-            logger.error(f"Exception: {ex}")
+            logger.error("Exception: %s" % ex)
         except socket.gaierror as ex:
-            logger.error(f"can't resolve address '{SEND_TO_ADDRESS}'")
+            logger.error("can't resolve address '%s'" % SEND_TO_ADDRESS)
         except Exception as ex:
             logger.exception("Unexpected exception during sending loop", exc_info=ex)
         finally:
-- 
2.17.1

